### ISSUE TITLE
Running tailored-lwb on multiple platforms

### ISSUE THREAD

**Issue by BowenWang** [csarkar/tailored-lwb#1]
Hi Chayan,
I am working on glossy and contiki right now. I just want to ask if your implementation can run on multiple platforms. We have 2 platforms right now: telosb and Zolertia Firefly.

Can this implementation run on multiple platforms? Thanks.

Bowen

**Comment by csarkar** [comment]
I have not tested it on any other platform except telosb. So not sure whether it will work on Zolertia. At least, the platform specific part of Glossy needs to be ported to the other platform that is not msp430.

**Comment by BowenWang** [comment]
All right, thanks.
